# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: trailing-whitespace
        exclude: .bumpversion.cfg
      - id: end-of-file-fixer
        exclude: .bumpversion.cfg
      - id: check-docstring-first
      - id: check-json
      - id: check-yaml
      - id: debug-statements
#      - id: name-tests-test
#        exclude: ^utils/
      - id: requirements-txt-fixer
      - id: double-quote-string-fixer
        exclude: ^protobuf/
      - id: check-added-large-files
  - repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.29.0
    hooks:
      - id: yapf
        args: ['--style=.style.yapf', '--parallel', '--in-place']
        exclude: models/
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
      - id: isort
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
      - id: flake8
