# Disable sudo to speed up the build
sudo: false

language: python

python: 3.7

# Install the codecov pip dependency
install:
  - pipenv install --dev

# Run the unit test
script:
  - pytest --cov=./

# Push the results back to codecov
after_success:
  - codecov

